### ISSUE TITLE
Extension not installable in phpBB 3.2.x

### ISSUE THREAD

**Issue by Crizz0** [Elsensee/phpbb-ext-posts-per-page#11]
The activation of this extension in version 1.0.1 leads to the following error:
```
SQL ERROR [ mysqli ]

Unknown column 'user_topics_sortby_dir' in 'phpbb_users' [1054]

SQL

ALTER TABLE `phpbb_users` ADD COLUMN `user_topics_per_page` smallint(4) UNSIGNED DEFAULT '0' NOT NULL AFTER user_topics_sortby_dir
```

phpBB 3.2.0
PHP 5.6

**Comment by Elsensee** [comment]
Can you try and replace the migration release_1_0_0_rc1.php with the version here on GitHub?

I'd really like to know, though, why it has worked in the past and how it was missed on validation,

**Comment by Crizz0** [comment]
With that file the installation is successful.

**Comment by Elsensee** [comment]
Thank you, I think I will submit the extension with that fix soon to the customisation database. :)

Does it work correctly on 3.2?

**Comment by Crizz0** [comment]
No. 

The settings here `ucp.php?i=ucp_prefs&mode=view` are not showing. 

Additionally, this description of the permission makes no sense:  
> Can set topic specific posts per page settings
Please note that this setting can only be set in the first post of a topic.

Regards

**Comment by Elsensee** [comment]
Alright, thank you. :)

What about that description is not clear to you?

**Comment by Crizz0** [comment]
But the settings are user specific global for the board. You change the topic per page in viewforum.php and the posts per page in the viewforum.php. 

But to different topics, different settings and obviously nothing can be set-up in the first-post of a topic. All settings are in the UCP.

**Comment by Elsensee** [comment]
In fact, they were supposed to also show up in the first post of a topic.
I presume a template event or so was changed or a php event.

It really did work that way in earlier versions of phpBB, I guess I have to check.

**Comment by Elsensee** [comment]
Could not reproduce this. All settings are displaying the way they should - and this is amazing regarding the fact I did not touch the code for three years.
