### ISSUE TITLE
services.yml doesn't following coding standard causing issue with phpBB 3.3.0-b1

### ISSUE THREAD

**Issue by nomind60s** [Elsensee/phpbb-ext-posts-per-page#15]
When testing the phpBB 3.3.0-b1 release I was receiving the error:

ext/elsensee/postsperpage/config/services.yml" does not contain valid YAML: The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 8 (near "- @auth").

When I checked the coding guidelines, https://area51.phpbb.com/docs/dev/3.2.x/extensions/tutorial_controllers.html#dependencies it shows the need to have quote marks.

**Comment by Elsensee** [comment]
Hi,

sorry, for not replying earlier. People have been notifying me now, I will look into it. :)

**Comment by nomind60s** [comment]
Thanks. My board users, particularly myself, love this extension and the functionality it adds to our board. So much so that I've long ago fixed the syntax when updating my boards to phpBB 3.3 (solution posted in https://www.phpbb.com/customise/db/extension/individual_posts_per_page/support/topic/211551) 

I've submitted a pull request with the required syntax changes to make the current code compliant with phpBB 3.3 requirements.

**Comment by nomind60s** [comment]
The requirement is covered in https://area51.phpbb.com/docs/dev/3.2.x/extensions/new_in_rhea.html#updated-symfony-services
