### ISSUE TITLE
Update arabic language

### ISSUE THREAD

**Issue by Elsensee** [Elsensee/phpbb-ext-posts-per-page#7]
Hey, since I added the requested feature a few hours ago the arabic language needs an update. So, if you want, @alhitary :smile:

I'm gonna check the code a bit before I plan to release the second release candidate tomorrow so do it whenever you can. No hassle! ;)

**Comment by alhitary** [comment]
Ok ,
Today inshaAllah ( God willing ) i'll update
Thanks brother

**Comment by Elsensee** [comment]
Every bug I knew about should be fixed now. :wink: 
That means that everything is feature complete. (And I really hope that I'm done now.. :grin: )

**Comment by alhitary** [comment]
Sorry brother for delay.
Minutes only and will start update the files.

**Comment by alhitary** [comment]
Hi Brother,

I finished update all but only one point is confused me. 
Plz let me ask you the following to understand the function and then i can translate professionally : 

1- "individual topics" : it means user's own topics ? i mean the topics which user post ? or it means specific/special topics ?
2- "topic specific posts" : can you explain this ? what does it mean ?

Your cooperation is highly appreciated and sorry to bother you

**Comment by Elsensee** [comment]
You don't bother me :smile: In fact, I almost thought that I would bother you :confused:  :grin:

Yeah these texts did need some thought and I still don't know if everybody could understand them but soon we will know. :grin:
1. "individual topics" means something like specific topics. Users with the required permission can set an individual post per page setting in the first post of a topic which only applies to that specific topic.
2. "topic specific posts" -> In the last commit I added a hyphen to make it more clear. It should have been "topic-specific posts per page (settings)". So "posts per page (settings)" is one term and "topic-specific" another term. For explanation see 1. :grin:

**Comment by alhitary** [comment]
Thanks alot dear Brother,
It's done and sent PR to you.

**Comment by Elsensee** [comment]
I have to thank **you** :)

Fixed by #8 and #9
